# Generated by Django 4.1.3 on 2022-11-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=200)),
                ('reminder', models.BooleanField(default=False)),
                ('day', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
